#!/bin/sh

set -eou pipefail


if cargo test --all; then
    echo '+cargo test --all'
if cargo clippy; then
    echo '+cargo clippy'
if cargo clippy --fix -Z unstable-options --allow-dirty --allow-staged; then
    echo '+clippy --fix -Z unstable-options --allow-dirty --allow-staged'
fi
