#!/bin/sh
#
# This hook was set by cargo-husky v1.5.0: https://github.com/rhysd/cargo-husky#readme
#
# This hook was set by cargo-husky v1.5.0: https://github.com/rhysd/cargo-husky#readme

set -eux

cargo clippy
cargo fmt
